### ISSUE TITLE
Error when reading remote CSV

### ISSUE THREAD

**Issue by phillipwongg** [CityOfLosAngeles/intake-dcat#14]
Results with following code:

```python
catalog = intake.open_catalog('remote_csv.yml') #reading in new YAML file with updated data
print(list(catalog))
```

```python
house = catalog.housing_data
housing = catalog.housing_data.read()
```

```yaml
metadata:
  version: 1
sources:        
  housing_data:  
    driver: csv 
    args:       
        urlpath: 'https://data.lacity.org/api/views/vxhy-r447/rows.csv?accessType=DOWNLOAD'
        csv_kwargs:             #allows me to download the file type without 'Bad URL error'
            blocksize: null       
            sample: false
  affordable_data: 
    driver: csv
    args:
        urlpath: 'https://data.lacity.org/api/views/u4mj-cwbz/rows.csv?accessType=DOWNLOAD'
        csv_kwargs:
            blocksize: null
            sample: false
```
